(function (win, ysp) {
  ysp.runtime.Model.extendLoadingModel({
    getData_control36: function (elem) {
      var data = [];var trs = $(elem).children('tr');for (var i = 1; i < trs.length; i++) {
        var obj = {};var tds = $(trs[i]).children('td');for (var j = 0; j < tds.length; j++) {
          obj.order = $(trs[i]).children('td').eq(1).children('a').eq(0).text();obj.state = $(trs[i]).children('td').eq(5).text();obj.orderType = $(trs[i]).children('td').eq(4).text();obj.time = $(trs[i]).children('td').eq(3).text().substr(0, 8);
        }data.push(obj);
      }console.log(data);return { 'data': data, 'title': ['销售订单号', '订单状态', '订单类型'], 'content': '示例条目' };
    },
    doAction_uiControl39: function (data, elem) {
      if (data.eventType == 'click') {
        var index = +data.dataCustom + 1;debugger;console.log($(elem).children('tr').eq(index).children('td:nth-child(2)').children('a').eq(0));$(elem).children('tr').eq(index).children('td:nth-child(2)').children('a').eq(0).click();
      }
    },
    getTemplate_uiControl39: function () {
      var selfTemplate = 'var React = require(\'react\');\n\nmodule.exports = React.createClass({\n  click(e){\n  \tvar handler=this.props.customHandler;\n    if(handler){\n    \thandler({\n      \tdata:e.target.dataset.id,\n        eventType:\'click\'\n      })\n    }\n  },\n  render: function(){\n    var data=this.props.data.customData||[];\n    var me=this;\n    var ul=data.data.map((item,i)=>{\n    \treturn(\n        <div className=\'orderList\'>\n          <ul>\n            <li>{data.title[0]}</li>\n            <li>{item.order}</li>\n          </ul>\n          <ul>\n            <li>{data.title[1]}</li>\n            <li>{item.state}</li>\n          </ul>\n          <div data-id={i} onClick={me.click}>{data.content}</div>\n          <ul>\n            <li>{data.title[2]}</li>\n            <li>{item.orderType}</li>\n          </ul>  \n          <span>{item.time}</span>\n        </div>\n      )\n    })\n    return (\n      <div>\n        {ul}\n      </div>\n    )\n  }\n});';
      return '\'use strict\';\n\nvar React = require(\'react\');\n\nmodule.exports = React.createClass({\n  displayName: \'exports\',\n  click: function click(e) {\n    var handler = this.props.customHandler;\n    if (handler) {\n      handler({\n        data: e.target.dataset.id,\n        eventType: \'click\'\n      });\n    }\n  },\n\n  render: function render() {\n    var data = this.props.data.customData || [];\n    var me = this;\n    var ul = data.data.map(function (item, i) {\n      return React.createElement(\n        \'div\',\n        { className: \'orderList\' },\n        React.createElement(\n          \'ul\',\n          null,\n          React.createElement(\n            \'li\',\n            null,\n            data.title[0]\n          ),\n          React.createElement(\n            \'li\',\n            null,\n            item.order\n          )\n        ),\n        React.createElement(\n          \'ul\',\n          null,\n          React.createElement(\n            \'li\',\n            null,\n            data.title[1]\n          ),\n          React.createElement(\n            \'li\',\n            null,\n            item.state\n          )\n        ),\n        React.createElement(\n          \'div\',\n          { \'data-id\': i, onClick: me.click },\n          data.content\n        ),\n        React.createElement(\n          \'ul\',\n          null,\n          React.createElement(\n            \'li\',\n            null,\n            data.title[2]\n          ),\n          React.createElement(\n            \'li\',\n            null,\n            item.orderType\n          )\n        ),\n        React.createElement(\n          \'span\',\n          null,\n          item.time\n        )\n      );\n    });\n    return React.createElement(\n      \'div\',\n      null,\n      ul\n    );\n  }\n});';
    }
  });
})(window, ysp);