(function (win, ysp) {
  ysp.runtime.Model.extendLoadingModel({
    getData_control20_E5aiXM: function (elem) {
      if (!elem) {
        return;
      }var content = ysp.customHelper.getTableData(elem, ['请求标题', '创建人', '创建日期', '接收日期', '工作流', '当前状况', '创建人部门', '所属公司', "紧急程度"]);return content;
    },
    doAction_uiControl20_W3PmsR: function (data, elem) {},
    getTemplate_uiControl20_W3PmsR: function () {
      var selfTemplate = 'module.exports = React.createClass({\n  render: function() {\n    var data = this.props.customData;\n    var item = data.content.map(function(d,i){\n      return (<section>\n          <div className=\'hthq_n1\'><div>{d[6]}</div><div>{d[5]}</div></div>\n          <div className=\'ht_n2\'><span>{data.titles[3]}</span><span>{d[3]}</span></div>\n          <div className=\'ht_n2\'><span>{data.titles[0]}</span><span>{d[0]}</span></div>\n          <div className=\'ht_n2\'><span>{data.titles[7]}</span><span>{d[7]}</span></div>\n          <div className=\'ht_n2\'><span>{data.titles[4]}</span><span>{d[4]}</span></div>\n          <div className=\'ht_n2\'><span>{data.titles[8]}</span><span>{d[8]}</span></div>\n          <div className=\'ht_n2\'><span>{data.titles[2]}</span><span>{d[2]}</span></div>\n          <div className=\'ht_n2\'><span>{data.titles[1]}</span><span>{d[1]}</span></div>\n        </section>)\n    })\n    return(<div className=\'table_hthq\'>{item}</div>)\n  }\n});';
      return '\'use strict\';\n\nmodule.exports = React.createClass({\n  displayName: \'exports\',\n\n  render: function render() {\n    var data = this.props.customData;\n    var item = data.content.map(function (d, i) {\n      return React.createElement(\n        \'section\',\n        null,\n        React.createElement(\n          \'div\',\n          { className: \'hthq_n1\' },\n          React.createElement(\n            \'div\',\n            null,\n            d[6]\n          ),\n          React.createElement(\n            \'div\',\n            null,\n            d[5]\n          )\n        ),\n        React.createElement(\n          \'div\',\n          { className: \'ht_n2\' },\n          React.createElement(\n            \'span\',\n            null,\n            data.titles[3]\n          ),\n          React.createElement(\n            \'span\',\n            null,\n            d[3]\n          )\n        ),\n        React.createElement(\n          \'div\',\n          { className: \'ht_n2\' },\n          React.createElement(\n            \'span\',\n            null,\n            data.titles[0]\n          ),\n          React.createElement(\n            \'span\',\n            null,\n            d[0]\n          )\n        ),\n        React.createElement(\n          \'div\',\n          { className: \'ht_n2\' },\n          React.createElement(\n            \'span\',\n            null,\n            data.titles[7]\n          ),\n          React.createElement(\n            \'span\',\n            null,\n            d[7]\n          )\n        ),\n        React.createElement(\n          \'div\',\n          { className: \'ht_n2\' },\n          React.createElement(\n            \'span\',\n            null,\n            data.titles[4]\n          ),\n          React.createElement(\n            \'span\',\n            null,\n            d[4]\n          )\n        ),\n        React.createElement(\n          \'div\',\n          { className: \'ht_n2\' },\n          React.createElement(\n            \'span\',\n            null,\n            data.titles[8]\n          ),\n          React.createElement(\n            \'span\',\n            null,\n            d[8]\n          )\n        ),\n        React.createElement(\n          \'div\',\n          { className: \'ht_n2\' },\n          React.createElement(\n            \'span\',\n            null,\n            data.titles[2]\n          ),\n          React.createElement(\n            \'span\',\n            null,\n            d[2]\n          )\n        ),\n        React.createElement(\n          \'div\',\n          { className: \'ht_n2\' },\n          React.createElement(\n            \'span\',\n            null,\n            data.titles[1]\n          ),\n          React.createElement(\n            \'span\',\n            null,\n            d[1]\n          )\n        )\n      );\n    });\n    return React.createElement(\n      \'div\',\n      { className: \'table_hthq\' },\n      item\n    );\n  }\n});';
    },
    getData_control2_G3dobM: function (elem) {},
    doAction_uiControl2_75zqOD: function (data, elem) {
      if (data.eventType == 'click') {
        ysp.customHelper.back();
      }
    },
    getTemplate_uiControl2_75zqOD: function () {
      var selfTemplate = 'import {Component} from \'react\'; \nimport {CommonHeader} from \'ysp-custom-components\';\nexport default class extends Component{\n  render(){\n    return (\n    \t<CommonHeader \n       data={{centerText:"01\u5408\u540C\u4F1A\u7B7E\u6D41\u7A0B"}} \n       backIsShow = {true}\n        back={(e)=>{\n          var handler = this.props.customHandler;\n          if(handler){\n            handler({\n              eventType:\'click\'\n            })\n          }\n        }}\n        />\n    )\t\n  }\n}';
      return '\'use strict\';\n\nObject.defineProperty(exports, "__esModule", {\n  value: true\n});\n\nvar _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();\n\nvar _react = require(\'react\');\n\nvar _yspCustomComponents = require(\'ysp-custom-components\');\n\nfunction _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }\n\nfunction _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn\'t been initialised - super() hasn\'t been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }\n\nfunction _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }\n\nvar _class = function (_Component) {\n  _inherits(_class, _Component);\n\n  function _class() {\n    _classCallCheck(this, _class);\n\n    return _possibleConstructorReturn(this, (_class.__proto__ || Object.getPrototypeOf(_class)).apply(this, arguments));\n  }\n\n  _createClass(_class, [{\n    key: \'render\',\n    value: function render() {\n      var _this2 = this;\n\n      return React.createElement(_yspCustomComponents.CommonHeader, {\n        data: { centerText: "01\u5408\u540C\u4F1A\u7B7E\u6D41\u7A0B" },\n        backIsShow: true,\n        back: function back(e) {\n          var handler = _this2.props.customHandler;\n          if (handler) {\n            handler({\n              eventType: \'click\'\n            });\n          }\n        }\n      });\n    }\n  }]);\n\n  return _class;\n}(_react.Component);\n\nexports.default = _class;';
    }
  });
})(window, ysp);